Repository sopt-makers/soptamp-android, pull requests merged in 2023-03, with the labels that each got.

#93 :bug: Add horizontal pager in mission detail screen
  app/src/main/java/org/sopt/stamp/feature/mission/detail/MissionDetail.kt
  app/src/main/java/org/sopt/stamp/feature/mission/model/ImageModel.kt
Labels: size/M

#94 ♻️ 단일 파일에 다수 컴포넌트가 존재했던 부분 수정
  app/src/main/java/org/sopt/stamp/feature/mission/detail/MissionDetail.kt
  app/src/main/java/org/sopt/stamp/feature/mission/detail/component/Header.kt
  app/src/main/java/org/sopt/stamp/feature/mission/detail/component/ImageContent.kt
  app/src/main/java/org/sopt/stamp/feature/mission/detail/component/Memo.kt
  app/src/main/java/org/sopt/stamp/feature/mission/detail/component/PostSubmissionBadge.kt
  app/src/main/java/org/sopt/stamp/feature/mission/model/ImageModel.kt
Labels: size/L

#97 미션 등록/수정/삭제 기능 구현 완료 및 개발자 QA
  app/src/main/java/org/sopt/stamp/data/remote/api/StampService.kt
  app/src/main/java/org/sopt/stamp/data/repository/StampRepositoryImpl.kt
  app/src/main/java/org/sopt/stamp/feature/mission/detail/MissionDetail.kt
  app/src/main/java/org/sopt/stamp/feature/mission/detail/MissionDetailViewModel.kt
  app/src/main/java/org/sopt/stamp/feature/mission/detail/component/DeleteStampDialog.kt
  app/src/main/java/org/sopt/stamp/feature/mission/detail/component/Header.kt
  app/src/main/java/org/sopt/stamp/feature/mission/detail/component/ImageContent.kt
  app/src/main/java/org/sopt/stamp/feature/mission/detail/component/Memo.kt
  app/src/main/java/org/sopt/stamp/feature/ranking/RankColor.kt
Labels: size/L

#98 설정화면 구현
  .github/workflows/develop_PR_builder.yml
  app/src/androidTest/java/org/sopt/stamp/ExampleInstrumentedTest.kt
  app/src/main/java/org/sopt/stamp/designsystem/component/toolbar/Toolbar.kt
  app/src/main/java/org/sopt/stamp/feature/mission/list/MissionListScreen.kt
  app/src/main/java/org/sopt/stamp/feature/mission/list/UserMissionListScreen.kt
  app/src/main/java/org/sopt/stamp/feature/ranking/RankingScreen.kt
  app/src/main/java/org/sopt/stamp/feature/setting/SettingScreen.kt
  app/src/main/java/org/sopt/stamp/feature/setting/SettingScreenViewModel.kt
  app/src/main/java/org/sopt/stamp/feature/setting/component/Header.kt
  app/src/main/java/org/sopt/stamp/feature/setting/component/Option.kt
  app/src/main/java/org/sopt/stamp/feature/setting/component/Section.kt
  app/src/main/java/org/sopt/stamp/feature/setting/model/SectionUiModel.kt
  app/src/main/res/drawable/arrow_left.xml
  app/src/main/res/drawable/arrow_right.xml
Labels: size/XL

#101 [feature/edit-introduction] 한 마디 편집 구현
  app/src/main/java/org/sopt/stamp/data/remote/api/RankService.kt
  app/src/main/java/org/sopt/stamp/data/remote/model/request/UpdateProfileMessageRequest.kt
  app/src/main/java/org/sopt/stamp/data/remote/source/RemoteUserDataSource.kt
  app/src/main/java/org/sopt/stamp/data/repository/RemoteUserRepository.kt
  app/src/main/java/org/sopt/stamp/data/source/UserDataSource.kt
  app/src/main/java/org/sopt/stamp/domain/usecase/UpdateProfileUseCase.kt
  app/src/main/java/org/sopt/stamp/feature/mission/detail/MissionDetail.kt
  app/src/main/java/org/sopt/stamp/feature/mission/detail/component/Memo.kt
  app/src/main/java/org/sopt/stamp/feature/setting/EditIntroductionScreen.kt
  app/src/main/java/org/sopt/stamp/feature/setting/EditIntroductionViewModel.kt
  app/src/main/java/org/sopt/stamp/feature/setting/SettingScreen.kt
  app/src/main/java/org/sopt/stamp/feature/setting/component/section/Header.kt
  app/src/main/java/org/sopt/stamp/feature/setting/component/section/Option.kt
  app/src/main/java/org/sopt/stamp/feature/setting/component/section/Section.kt
  app/src/main/java/org/sopt/stamp/util/FocusUtil.kt
Labels: size/L

#102 [feature/user-withdraw] 회원탈퇴 기능 구현
  app/src/main/java/org/sopt/stamp/domain/usecase/auth/AutoLoginUseCase.kt
  app/src/main/java/org/sopt/stamp/domain/usecase/auth/GetUserIdUseCase.kt
  app/src/main/java/org/sopt/stamp/domain/usecase/auth/WithdrawalUseCase.kt
  app/src/main/java/org/sopt/stamp/domain/usecase/user/UpdateProfileUseCase.kt
  app/src/main/java/org/sopt/stamp/feature/login/SoptampLoginViewModel.kt
  app/src/main/java/org/sopt/stamp/feature/setting/SettingScreen.kt
  app/src/main/java/org/sopt/stamp/feature/setting/SettingScreenViewModel.kt
  app/src/main/java/org/sopt/stamp/feature/setting/profile/UpdateProfileScreen.kt
  app/src/main/java/org/sopt/stamp/feature/setting/profile/UpdateProfileViewModel.kt
  app/src/main/java/org/sopt/stamp/feature/setting/withdrawal/WithdrawalScreen.kt
  app/src/main/java/org/sopt/stamp/feature/setting/withdrawal/WithdrawalScreenViewModel.kt
Labels: size/L

#103 :bug: 탈퇴화면으로 안 넘어가는 현상 수정
  app/src/main/java/org/sopt/stamp/feature/setting/SettingScreen.kt
  app/src/main/java/org/sopt/stamp/feature/setting/withdrawal/WithdrawalScreen.kt
Labels: size/M

#104 닉네임 변경 기능
  .github/workflows/develop_merge_builder.yml
  app/src/main/java/org/sopt/stamp/data/remote/api/UserService.kt
  app/src/main/java/org/sopt/stamp/data/remote/source/RemoteUserDataSource.kt
  app/src/main/java/org/sopt/stamp/data/repository/RemoteUserRepository.kt
  app/src/main/java/org/sopt/stamp/data/source/UserDataSource.kt
  app/src/main/java/org/sopt/stamp/domain/fake/FakeUserRepository.kt
  app/src/main/java/org/sopt/stamp/domain/repository/UserRepository.kt
  app/src/main/java/org/sopt/stamp/domain/usecase/user/CheckNicknameDuplicateUseCase.kt
  app/src/main/java/org/sopt/stamp/domain/usecase/user/UpdateNicknameUseCase.kt
  app/src/main/java/org/sopt/stamp/feature/setting/SettingScreen.kt
  app/src/main/java/org/sopt/stamp/feature/setting/nickname/UpdateNicknameScreen.kt
  app/src/main/java/org/sopt/stamp/feature/setting/nickname/UpdateNicknameViewModel.kt
  app/src/main/java/org/sopt/stamp/feature/setting/withdrawal/WithdrawalScreen.kt
  app/src/main/java/org/sopt/stamp/feature/signup/SoptampSignUpViewModel.kt
Labels: size/L

#105 :bug: 로그인/회원가입 QA
  app/src/main/java/org/sopt/stamp/data/remote/api/UserService.kt
  app/src/main/java/org/sopt/stamp/data/remote/source/RemoteUserDataSource.kt
  app/src/main/java/org/sopt/stamp/data/repository/UserRepositoryImpl.kt
  app/src/main/java/org/sopt/stamp/data/source/UserDataSource.kt
  app/src/main/java/org/sopt/stamp/designsystem/component/layout/Layout.kt
  app/src/main/java/org/sopt/stamp/di/DataModule.kt
  app/src/main/java/org/sopt/stamp/domain/fake/FakeUserRepository.kt
  app/src/main/java/org/sopt/stamp/domain/repository/UserRepository.kt
  app/src/main/java/org/sopt/stamp/feature/login/LoginUiState.kt
  app/src/main/java/org/sopt/stamp/feature/login/LoginViewModel.kt
  app/src/main/java/org/sopt/stamp/feature/login/component/LoginTextField.kt
  app/src/main/java/org/sopt/stamp/feature/login/screen/LoginScreen.kt
  app/src/main/java/org/sopt/stamp/feature/signup/SignUpUiState.kt
  app/src/main/java/org/sopt/stamp/feature/signup/SignUpViewModel.kt
  app/src/main/java/org/sopt/stamp/feature/signup/component/PasswordTextField.kt
  app/src/main/java/org/sopt/stamp/feature/signup/component/SignUpInputContainer.kt
  app/src/main/java/org/sopt/stamp/feature/signup/component/SignUpTextField.kt
  app/src/main/java/org/sopt/stamp/feature/signup/screen/SignUpScreen.kt
  app/src/main/java/org/sopt/stamp/feature/signup/screen/SoptampSignUpScreen.kt
Labels: size/XXL

#108 :wrench: wrote release distribution script
  .github/workflows/release.yml
Labels: size/M

#109 :memo: Add document and license
  LICENSE.md
  README.md
Labels: size/M

#114 :docs: update docs
  README.md
Labels: size/XS

#118 fix: 반환타입 Response<T>인 Service 인터페이스에 대하여 유효성 검사 로직 추가
  app/src/main/java/org/sopt/stamp/data/remote/source/RemoteUserDataSource.kt
Labels: size/M

#121 :bug: 미션 작성과 관련된 서버통신/UI 에러 수정
  app/build.gradle
  app/src/debug/java/org/sopt/stamp/FlipperInitializer.kt
  app/src/main/java/org/sopt/stamp/data/remote/api/StampService.kt
  app/src/main/java/org/sopt/stamp/data/repository/StampRepositoryImpl.kt
  app/src/main/java/org/sopt/stamp/domain/fake/FakeStampRepository.kt
  app/src/main/java/org/sopt/stamp/domain/repository/StampRepository.kt
  app/src/main/java/org/sopt/stamp/feature/mission/MissionsViewModel.kt
  app/src/main/java/org/sopt/stamp/feature/mission/detail/MissionDetail.kt
  app/src/main/java/org/sopt/stamp/feature/mission/detail/MissionDetailViewModel.kt
  app/src/main/java/org/sopt/stamp/feature/mission/list/MissionListScreen.kt
  app/src/main/java/org/sopt/stamp/feature/mission/list/UserMissionListScreen.kt
  app/src/main/java/org/sopt/stamp/feature/mission/model/MissionNavArgs.kt
  app/src/release/java/org/sopt/stamp/FlipperInitializer.kt
Labels: size/L

#122 2차 QA 반영
  .gitignore
  app/src/main/java/org/sopt/stamp/data/local/SoptampDataStore.kt
  app/src/main/java/org/sopt/stamp/data/repository/StampRepositoryImpl.kt
  app/src/main/java/org/sopt/stamp/data/repository/UserRepositoryImpl.kt
  app/src/main/java/org/sopt/stamp/designsystem/component/toolbar/Toolbar.kt
  app/src/main/java/org/sopt/stamp/domain/fake/FakeUserRepository.kt
  app/src/main/java/org/sopt/stamp/domain/repository/UserRepository.kt
  app/src/main/java/org/sopt/stamp/feature/login/LoginViewModel.kt
  app/src/main/java/org/sopt/stamp/feature/login/component/OnboardingPage.kt
  app/src/main/java/org/sopt/stamp/feature/login/component/PagingIndicator.kt
  app/src/main/java/org/sopt/stamp/feature/login/screen/LoginScreen.kt
  app/src/main/java/org/sopt/stamp/feature/login/screen/OnboardingScreen.kt
  app/src/main/java/org/sopt/stamp/feature/mission/detail/MissionDetail.kt
  app/src/main/java/org/sopt/stamp/feature/mission/detail/MissionDetailViewModel.kt
  app/src/main/java/org/sopt/stamp/feature/mission/detail/component/Header.kt
  app/src/main/java/org/sopt/stamp/feature/mission/detail/component/ImageContent.kt
  app/src/main/java/org/sopt/stamp/feature/mission/detail/component/Memo.kt
  app/src/main/java/org/sopt/stamp/feature/ranking/RankColor.kt
  app/src/main/java/org/sopt/stamp/util/ContentUriRequestBody.kt
  app/src/main/res/drawable/ic_onboarding_1.xml
  app/src/main/res/drawable/ic_onboarding_2.xml
  app/src/main/res/drawable/ic_onboarding_3.xml
Labels: size/XL

#126 회원가입 화면 기능 구현
  app/src/main/java/org/sopt/stamp/data/remote/api/UserService.kt
  app/src/main/java/org/sopt/stamp/data/remote/model/response/SignUpResponse.kt
  app/src/main/java/org/sopt/stamp/data/remote/source/RemoteUserDataSource.kt
  app/src/main/java/org/sopt/stamp/data/repository/UserRepositoryImpl.kt
  app/src/main/java/org/sopt/stamp/data/source/UserDataSource.kt
  app/src/main/java/org/sopt/stamp/designsystem/component/button/SoptampButton.kt
  app/src/main/java/org/sopt/stamp/designsystem/component/dialog/ErrorDialog.kt
  app/src/main/java/org/sopt/stamp/designsystem/component/dialog/NetworkErrorDialog.kt
  app/src/main/java/org/sopt/stamp/designsystem/component/textfield/SoptampTextField.kt
  app/src/main/java/org/sopt/stamp/designsystem/component/topappbar/SoptTopAppBar.kt
  app/src/main/java/org/sopt/stamp/designsystem/style/Theme.kt
  app/src/main/java/org/sopt/stamp/domain/fake/FakeUserRepository.kt
  app/src/main/java/org/sopt/stamp/domain/repository/UserRepository.kt
  app/src/main/java/org/sopt/stamp/feature/signup/SignUpViewModel.kt
  app/src/main/java/org/sopt/stamp/feature/signup/component/RegisterInputField.kt
  app/src/main/java/org/sopt/stamp/feature/signup/component/RegisterPasswordInputField.kt
  app/src/main/java/org/sopt/stamp/feature/signup/model/CheckState.kt
  app/src/main/java/org/sopt/stamp/feature/signup/model/RegisterState.kt
  app/src/main/java/org/sopt/stamp/feature/signup/model/RegisterUiModel.kt
  app/src/main/java/org/sopt/stamp/feature/signup/screen/SignUpCompleteScreen.kt
  app/src/main/java/org/sopt/stamp/feature/signup/screen/SignUpScreen.kt
  app/src/main/java/org/sopt/stamp/util/KeyBoardState.kt
  app/src/main/java/org/sopt/stamp/util/validation/Email.kt
  app/src/main/java/org/sopt/stamp/util/validation/Nickname.kt
  app/src/main/java/org/sopt/stamp/util/validation/Password.kt
  app/src/main/java/org/sopt/stamp/util/validation/Verifiable.kt
  app/src/main/res/drawable/register_complete.xml
Labels: size/XXL

#127 [feature/ranking-qa]
  app/src/main/java/org/sopt/stamp/feature/mission/detail/MissionDetail.kt
  app/src/main/java/org/sopt/stamp/feature/mission/detail/component/Header.kt
  app/src/main/java/org/sopt/stamp/feature/mission/detail/component/Memo.kt
  app/src/main/java/org/sopt/stamp/feature/ranking/RankColor.kt
  app/src/main/java/org/sopt/stamp/feature/ranking/RankingScreen.kt
  app/src/main/java/org/sopt/stamp/feature/ranking/RankingViewModel.kt
Labels: size/L

#136 :technologist: feature/#116 Sentry 설정
  .github/workflows/develop_PR_builder.yml
  .github/workflows/develop_merge_builder.yml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  build.gradle.kts
  gradle/libs.versions.toml
Labels: size/M

#138 :sparkles: 네트워크 에러 발생할 때 에러 팝업 띄워주기
  app/src/main/java/org/sopt/stamp/designsystem/component/dialog/ErrorDialog.kt
  app/src/main/java/org/sopt/stamp/designsystem/component/dialog/SingleOptionDialog.kt
  app/src/main/java/org/sopt/stamp/feature/mission/detail/MissionDetail.kt
  app/src/main/java/org/sopt/stamp/feature/mission/detail/MissionDetailViewModel.kt
Labels: size/L

#139 [feature/error-linter] Linter error fix
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/sopt/stamp/designsystem/component/dialog/SingleOptionDialog.kt
  app/src/main/java/org/sopt/stamp/feature/mission/detail/MissionDetail.kt
Labels: size/XS
