Repository sopt-makers/soptamp-android, pull requests merged in 2023-01, with the labels that each got.

#35 [feature/net-module] 네트워크 모듈 쪽 Config
  .github/workflows/develop_PR_builder.yml
  .github/workflows/develop_merge_builder.yml
  .gitignore
  app/build.gradle
  app/src/main/java/org/sopt/stamp/data/model/request/.gitkeep
  app/src/main/java/org/sopt/stamp/data/model/response/ResponseModifyStampDto.kt
  app/src/main/java/org/sopt/stamp/data/model/response/ResponseStampDto.kt
  app/src/main/java/org/sopt/stamp/data/remote/service/StampService.kt
  app/src/main/java/org/sopt/stamp/di/ConfigModule.kt
  app/src/main/java/org/sopt/stamp/di/ConstantModule.kt
  app/src/main/java/org/sopt/stamp/di/RemoteModule.kt
  app/src/main/java/org/sopt/stamp/di/constant/Constant.kt
  gradle/libs.versions.toml
Labels: size/L

#37 [feature/new-remote-mission-list] 미션 리스트 서버 통신
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/sopt/stamp/data/mapper/MissionsMapper.kt
  app/src/main/java/org/sopt/stamp/data/remote/api/SoptampService.kt
  app/src/main/java/org/sopt/stamp/data/remote/mapper/MissionsMapper.kt
  app/src/main/java/org/sopt/stamp/data/remote/model/MissionData.kt
  app/src/main/java/org/sopt/stamp/data/remote/model/MissionsData.kt
  app/src/main/java/org/sopt/stamp/data/remote/model/response/MissionResponse.kt
  app/src/main/java/org/sopt/stamp/data/remote/model/response/MissionsResponse.kt
  app/src/main/java/org/sopt/stamp/data/remote/source/RemoteMissionsDataSource.kt
  app/src/main/java/org/sopt/stamp/data/repository/RemoteMissionsRepository.kt
  app/src/main/java/org/sopt/stamp/data/source/MissionsDataSource.kt
  app/src/main/java/org/sopt/stamp/designsystem/component/dialog/NetworkErrorDialog.kt
  app/src/main/java/org/sopt/stamp/di/DataModule.kt
  app/src/main/java/org/sopt/stamp/di/DataSourceModule.kt
  app/src/main/java/org/sopt/stamp/domain/model/Mission.kt
  app/src/main/java/org/sopt/stamp/domain/model/Missions.kt
  app/src/main/java/org/sopt/stamp/domain/model/MissionsFilter.kt
  app/src/main/java/org/sopt/stamp/domain/repository/MissionsRepository.kt
  app/src/main/java/org/sopt/stamp/feature/mission/MissionListScreen.kt
  app/src/main/java/org/sopt/stamp/feature/mission/MissionsActivity.kt
  app/src/main/java/org/sopt/stamp/feature/mission/MissionsViewModel.kt
  app/src/main/java/org/sopt/stamp/feature/mission/model/MissionListUiModel.kt
Labels: size/L

#38 Feature/ranking 랭킹 뷰 구현 내용
  app/src/main/java/org/sopt/stamp/data/remote/api/SoptampService.kt
  app/src/main/java/org/sopt/stamp/data/remote/model/MissionData.kt
  app/src/main/java/org/sopt/stamp/data/remote/model/response/MissionResponse.kt
  app/src/main/java/org/sopt/stamp/feature/detail/MissionDetail.kt
  app/src/main/java/org/sopt/stamp/feature/mission/MissionListScreen.kt
  app/src/main/java/org/sopt/stamp/feature/mission/MissionsViewModel.kt
  app/src/main/java/org/sopt/stamp/feature/ranking/RankColor.kt
  app/src/main/java/org/sopt/stamp/feature/ranking/RankListItem.kt
  app/src/main/java/org/sopt/stamp/feature/ranking/RankNumber.kt
  app/src/main/java/org/sopt/stamp/feature/ranking/RankScore.kt
  app/src/main/java/org/sopt/stamp/feature/ranking/RankingScreen.kt
  app/src/main/java/org/sopt/stamp/feature/ranking/TopRankerItem.kt
  app/src/main/java/org/sopt/stamp/feature/ranking/TopRankerList.kt
  app/src/main/java/org/sopt/stamp/feature/ranking/model/RankerUiModel.kt
  app/src/main/java/org/sopt/stamp/feature/ranking/model/RankingListUiModel.kt
  app/src/main/java/org/sopt/stamp/feature/ranking/model/TopRankerDescriptionBubble.kt
  app/src/main/res/drawable/bubble_left.xml
  app/src/main/res/drawable/bubble_middle.xml
  app/src/main/res/drawable/bubble_right.xml
Labels: size/XL

#39 [feature/navigation-config] Navigation Library Config
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/sopt/stamp/App.kt
  app/src/main/java/org/sopt/stamp/MainActivity.kt
  app/src/main/java/org/sopt/stamp/config/initializer/MavericksInitializer.kt
  app/src/main/java/org/sopt/stamp/config/initializer/TimberInitializer.kt
  app/src/main/java/org/sopt/stamp/config/navigation/NavHosts.kt
  app/src/main/java/org/sopt/stamp/feature/mission/MissionListScreen.kt
  app/src/main/java/org/sopt/stamp/feature/mission/MissionsActivity.kt
  gradle/libs.versions.toml
Labels: size/L

#40 [feature/flipper-config] Flipper Config
  app/src/main/java/org/sopt/stamp/App.kt
  app/src/main/java/org/sopt/stamp/di/ConfigModule.kt
  app/src/main/java/org/sopt/stamp/di/Interceptor.kt
Labels: size/M

#42 [Feature/signup/presentation] 회원가입 presentation 구현
  app/src/main/java/org/sopt/stamp/feature/signup/SoptampSignUpViewModel.kt
  app/src/main/java/org/sopt/stamp/feature/signup/SoptampSignUpViewState.kt
  app/src/main/java/org/sopt/stamp/feature/signup/screen/SoptampSignUpScreen.kt
Labels: size/L

#34 [Feature/login/presentation] 로그인 presentation 구현
  app/src/main/java/org/sopt/stamp/login/SoptampLoginViewModel.kt
  app/src/main/java/org/sopt/stamp/login/SoptampLoginViewState.kt
  app/src/main/java/org/sopt/stamp/login/screen/SoptampLoginScreen.kt
  app/src/main/res/drawable/ic_soptamp.xml
Labels: size/L

#44 [Feature/login&&signup] 로그인 및 회원가입 서버 통신 구현 및 뷰 모델 연결
  app/src/main/java/org/sopt/stamp/data/remote/api/UserService.kt
  app/src/main/java/org/sopt/stamp/data/remote/model/response/UserResponse.kt
  app/src/main/java/org/sopt/stamp/data/remote/source/RemoteUserDataSource.kt
  app/src/main/java/org/sopt/stamp/data/repository/RemoteUserRepository.kt
  app/src/main/java/org/sopt/stamp/data/source/UserDataSource.kt
  app/src/main/java/org/sopt/stamp/domain/repository/UserRepository.kt
  app/src/main/java/org/sopt/stamp/feature/login/SoptampLoginViewModel.kt
  app/src/main/java/org/sopt/stamp/feature/login/SoptampLoginViewState.kt
  app/src/main/java/org/sopt/stamp/feature/login/screen/SoptampLoginScreen.kt
  app/src/main/java/org/sopt/stamp/feature/signup/SoptampSignUpViewModel.kt
  app/src/main/java/org/sopt/stamp/feature/signup/SoptampSignUpViewState.kt
  app/src/main/java/org/sopt/stamp/login/SoptampLoginViewModel.kt
  app/src/main/java/org/sopt/stamp/login/SoptampLoginViewState.kt
  app/src/main/java/org/sopt/stamp/login/screen/SoptampLoginScreen.kt
Labels: size/XL

#41 [feature/detail-screen] 미션 상세 화면 연결 및 서버통신
  app/src/main/java/org/sopt/stamp/data/remote/api/StampService.kt
  app/src/main/java/org/sopt/stamp/data/remote/model/response/StampResponse.kt
  app/src/main/java/org/sopt/stamp/data/repository/StampRepositoryImpl.kt
  app/src/main/java/org/sopt/stamp/designsystem/component/mission/MissionComponent.kt
  app/src/main/java/org/sopt/stamp/di/DataModule.kt
  app/src/main/java/org/sopt/stamp/domain/model/Archive.kt
  app/src/main/java/org/sopt/stamp/domain/repository/StampRepository.kt
  app/src/main/java/org/sopt/stamp/feature/mission/detail/MissionDetail.kt
  app/src/main/java/org/sopt/stamp/feature/mission/detail/MissionDetailViewModel.kt
  app/src/main/java/org/sopt/stamp/feature/mission/list/MissionListScreen.kt
  app/src/main/java/org/sopt/stamp/feature/mission/model/ImageModel.kt
  app/src/main/java/org/sopt/stamp/feature/mission/model/MissionListUiModel.kt
  app/src/main/java/org/sopt/stamp/feature/mission/model/MissionNavArgs.kt
  app/src/main/java/org/sopt/stamp/feature/mission/model/MissionUiModel.kt
  app/src/main/java/org/sopt/stamp/util/ContentUriRequestBody.kt
Labels: size/XL

#51 [feature/fix-navigation-issue] change ksp build sourceset
  app/build.gradle
Labels: size/XS

#54 [feature/change-jvmargs] 빌드 최적화 위한 jvmargs 수정
  gradle.properties
Labels: size/XS

#55 👍🏻 Bump Dependencies
  gradle/libs.versions.toml
Labels: size/S

#56 [feature/destination] Bump Dependencies
  gradle/libs.versions.toml
Labels: size/XS

#57 [Feature/login/viewmodel] 로그인 화면 - 뷰모델 연결
  app/src/main/java/org/sopt/stamp/App.kt
  app/src/main/java/org/sopt/stamp/MainActivity.kt
  app/src/main/java/org/sopt/stamp/config/navigation/NavHosts.kt
  app/src/main/java/org/sopt/stamp/data/remote/api/UserService.kt
  app/src/main/java/org/sopt/stamp/data/remote/model/request/LoginRequest.kt
  app/src/main/java/org/sopt/stamp/data/remote/model/request/SignUpRequest.kt
  app/src/main/java/org/sopt/stamp/data/remote/model/response/UserResponse.kt
  app/src/main/java/org/sopt/stamp/data/remote/source/RemoteUserDataSource.kt
  app/src/main/java/org/sopt/stamp/di/DataModule.kt
  app/src/main/java/org/sopt/stamp/di/DataSourceModule.kt
  app/src/main/java/org/sopt/stamp/di/RemoteModule.kt
  app/src/main/java/org/sopt/stamp/feature/login/SoptampLoginViewModel.kt
  app/src/main/java/org/sopt/stamp/feature/login/SoptampLoginViewState.kt
  app/src/main/java/org/sopt/stamp/feature/login/screen/SoptampLoginScreen.kt
  app/src/main/java/org/sopt/stamp/feature/mission/list/MissionListScreen.kt
  app/src/main/java/org/sopt/stamp/feature/signup/SoptampSignUpViewModel.kt
  app/src/main/java/org/sopt/stamp/feature/signup/screen/SoptampSignUpScreen.kt
Labels: size/L

#60 [feature/nunu/sharedpreference] SoptampDataStore 수정
  app/src/main/java/org/sopt/stamp/App.kt
  app/src/main/java/org/sopt/stamp/data/local/SoptampDataStore.kt
  app/src/main/java/org/sopt/stamp/feature/login/SoptampLoginViewModel.kt
Labels: size/S

#59 [Feature/login/sharedpreference] SoptampDataStoreModule 구성
  app/build.gradle
  app/src/main/java/org/sopt/stamp/data/local/SoptampDataStore.kt
  app/src/main/java/org/sopt/stamp/data/remote/model/response/UserResponse.kt
  app/src/main/java/org/sopt/stamp/domain/model/User.kt
  app/src/main/java/org/sopt/stamp/feature/login/SoptampLoginViewModel.kt
Labels: size/M

#66 fix: 터치 영역 > 표시 까지 확장
  app/src/main/java/org/sopt/stamp/feature/ranking/TopRankerList.kt
Labels: size/XS

#67 Hotfix/64 mission stamp lottie to image
  app/src/main/java/org/sopt/stamp/designsystem/component/mission/CompletedStamp.kt
  app/src/main/java/org/sopt/stamp/designsystem/component/mission/MissionComponent.kt
  app/src/main/java/org/sopt/stamp/designsystem/component/mission/Stamp.kt
  app/src/main/res/drawable/greenstamp_image.xml
  app/src/main/res/drawable/pinkstamp_image.xml
  app/src/main/res/drawable/purplestamp_image.xml
Labels: size/L

#68 fix: 미션 디테일 필터 수정
  app/src/main/java/org/sopt/stamp/feature/mission/list/UserMissionListScreen.kt
Labels: size/XS

#69 Hotfix/ranking
  app/src/main/java/org/sopt/stamp/feature/mission/MissionsViewModel.kt
  app/src/main/java/org/sopt/stamp/feature/mission/list/MissionListScreen.kt
  app/src/main/java/org/sopt/stamp/feature/ranking/RankListItem.kt
  app/src/main/java/org/sopt/stamp/feature/ranking/RankNumber.kt
Labels: size/L
